"use client";
import router from "next/router";
import React, { useState, useEffect } from "react";

interface Question {
  id: number;
  text: string;
  options: string[];
}

const Quiz: React.FC = () => {
  const questions: Question[] = [
    {
      id: 1,
      text: "Would you rather spend 10 hours a day...",
      options: ["Producing Enjoyable Content", "Studying charts and numbers"]
    },
    {
      id: 2,
      text: "Are you more Extrovert or Introvert?",
      options: ["Extrovert", "Introvert"]
    },
    {
      id: 3,
      text: "How do you approach solving challenges?",
      options: ["Making content to address the issues", "Analyzing the market for decision making"]
    },
    {
      id: 4,
      text: "What excites you most about your work?",
      options: ["Seeing people engage with the content I create", "Successfully predicting outcomes"]
    },
    {
      id: 5,
      text: "How do you measure success in your work?",
      options: ["By building a scalable and efficient model for future growth", "By the emotional impact or engagement generated by prospects"]
    },
    {
      id: 6,
      text: "You’ve been given the opportunity to teach your skills to others. What would you focus on?",
      options: ["How to craft a compelling YouTube channel to build a loyal online audience", "How to identify patterns and execute trades with precision under pressure"]
    },
    {
      id: 7,
      text: "How would you convince someone?",
      options: ["Using public information", "Creating an exposé in the form of a video"]
    }
  ];

  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedOptions, setSelectedOptions] = useState<string[]>([]);
  const [timeLeft, setTimeLeft] = useState(15); // Timer for each question
  const [quizCompleted, setQuizCompleted] = useState(false);
  const [timeUp, setTimeUp] = useState(false);

  // Handle timer for each question
  useEffect(() => {
    if (timeLeft > 0 && !quizCompleted) {
      const timer = setTimeout(() => setTimeLeft(timeLeft - 1), 1000);
      return () => clearTimeout(timer);
    } else if (timeLeft === 0 && !quizCompleted) {
      setTimeUp(true);
    }
  }, [timeLeft, quizCompleted]);

  const handleOptionSelect = (option: string) => {
    const updatedSelections = [...selectedOptions];
    updatedSelections[currentQuestionIndex] = option;
    setSelectedOptions(updatedSelections);
  };

  const handleNext = () => {
    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex(currentQuestionIndex + 1);
      setTimeLeft(15); // Reset timer for next question
      setTimeUp(false); // Reset time-up status
    } else {
      setQuizCompleted(true);
    }
  };

  const handleRetakeQuiz = () => {
    setCurrentQuestionIndex(0);
    setSelectedOptions([]);
    setTimeLeft(15);
    setQuizCompleted(false);
    setTimeUp(false);
  };

  const handleViewResults = () => {
    router.push("/results");
  };

  const progress = ((currentQuestionIndex + 1) / questions.length) * 100;

  const currentQuestion = questions[currentQuestionIndex];

  return (
    <div
      className="min-h-screen flex justify-center items-center text-white"
      style={{
        backgroundImage: "url('/background.png')",
        backgroundSize: "cover",
        backgroundPosition: "center",
      }}
    >
      {!quizCompleted ? (
        <div className="max-w-md w-full p-6 bg-gray-800 bg-opacity-80 rounded-md shadow-lg">
          <h2 className="text-lg font-bold text-center mb-4">
            CONTENT CREATION AND TRADING
          </h2>

          {/* Timer */}
          {!timeUp && (
            <div className="text-center mb-4">
              <p className="text-lg font-bold">
                Time Left: <span className="text-yellow-500">{timeLeft}s</span>
              </p>
            </div>
          )}

          {/* Progress Bar */}
          <div className="relative w-full h-4 bg-gray-600 rounded-full mb-4">
            <div
              className="absolute top-0 left-0 h-4 bg-yellow-500 rounded-full"
              style={{ width: `${progress}%` }}
            ></div>
          </div>

          {/* Question and Options */}
          {!timeUp ? (
            <div className="mb-6">
              <h3 className="text-xl font-semibold text-center mb-4">
                {currentQuestion.text}
              </h3>
              <div className="space-y-4">
                {currentQuestion.options.map((option, index) => (
                  <button
                    key={index}
                    onClick={() => handleOptionSelect(option)}
                    className={`block w-full py-3 px-4 text-center rounded-lg font-medium ${
                      selectedOptions[currentQuestionIndex] === option
                        ? "bg-yellow-500 text-gray-900"
                        : "bg-gray-700 hover:bg-gray-600"
                    }`}
                  >
                    {option}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className="text-center mb-6">
              <h3 className="text-xl font-semibold text-red-500 mb-4">
                Time is up!
              </h3>
            </div>
          )}

          {/* Next Button */}
          {!timeUp && (
            <button
              onClick={handleNext}
              className="w-full py-3 px-4 bg-yellow-500 text-gray-900 font-bold rounded-md hover:bg-yellow-400"
            >
              {currentQuestionIndex < questions.length - 1 ? "NEXT" : "FINISH"}
            </button>
          )}
        </div>
      ) : (
        <div className="max-w-md w-full p-6 bg-gray-800 bg-opacity-80 rounded-md shadow-lg text-center">
          <h2 className="text-xl font-bold mb-4">Quiz Completed!</h2>
          <p className="mb-6">Thank you for completing the quiz.</p>
          <button
              onClick={handleViewResults}
              className="px-6 py-3 bg-yellow-500 text-black rounded-md hover:bg-yellow-400 mb-4"
            >
              View Results
            </button>

          <button
            onClick={handleRetakeQuiz}
            className="w-full py-3 px-4 bg-gray-700 text-white font-bold rounded-md hover:bg-gray-600"
          >
            Retake Quiz
          </button>
        </div>
      )}
    </div>
  );
};

export default Quiz;
